Django_Project/Django/Dev/ecommercefirst/src/carts/urls.py
from django.conf.urls.static import static

from django.urls import path, include # new

from .views import (
			    cart_home,
			    cart_update,
			    checkout_home,
			    checkout_done_view,
                    )
urlpatterns = [
    path(r'',cart_home,name="home"),
    path(r'update/',cart_update,name="update"),
    path(r'checkout/',checkout_home,name="checkout"),
    path(r'checkout/success/',checkout_done_view,name="success"),
  ]

Django_Project/Django/Dev/ecommercefirst/src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include # new

from django.contrib.auth.views import LogoutView

from accounts.views import login_page,register_page,guest_register_view
from addresses.views import checkout_address_create_view,checkout_address_reuse_view

from .views import home_page_old,home_page_new,home_page,contact_page,about_page


# from products.views import (
#     ProductListView,
#     product_list_view,
#     ProductDetailView,
#     ProductDetailSlugView,
#     product_detail_view,
#     ProductFeaturedListView,
#     ProductFeaturedDetailView
#                             )

urlpatterns = [
	path(r'',home_page),
    path(r'old/', home_page_old),
    path(r'home/', home_page_new,name="home"),
    path(r'contact/', contact_page,name="contact"),
    path(r'login/', login_page,name="login"),
    path(r'checkout/address/create/', checkout_address_create_view,name="checkout_address_create"),
    path(r'checkout/address/reuse/', checkout_address_reuse_view,name="checkout_address_reuse"),
    path(r'register/guest/', guest_register_view,name="guest_register"),
    path(r'logout/', LogoutView.as_view(),name="logout"),
    path(r'register/', register_page,name="register"),
    path(r'about/', about_page,name="blog"),
    path(r'products/', include( ("products.urls","products"),namespace="products")),
    path(r'search/', include( ("search.urls","search"),namespace="search")),
    path(r'cart/', include( ("carts.urls","cart"),namespace="cart")),
    # path(r'featured/', ProductFeaturedListView.as_view()), # gets os errors name wrng means
    # path(r'products-fb/', product_list_view),
    # path(r'products/<int:pk>/', ProductDetailView.as_view()),
    # path(r'products/<slug:slug>/', ProductDetailSlugView.as_view()),
    # path(r'featured/<int:pk>/', ProductFeaturedDetailView.as_view()),
    # path(r'products-fb/<int:pk>/', product_detail_view),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
	urlpatterns =urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns =urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_Project/Django/Dev/ecommercefirst/src/carts/models.py
from django.db import models
from django.conf import settings


from django.db.models.signals import pre_save,post_save,m2m_changed
from products.models import Product
# Create your models here.

User=settings.AUTH_USER_MODEL

class CartManager(models.Manager):
	def new_or_get(self,request):
		cart_id=request.session.get("cart_id",None)
		qs = self.get_queryset().filter(id=cart_id)
		print(str(qs.count())+"this is hell!!!!" )
		if qs.count() == 1:
			new_obj=False
			cart_obj =qs.first()
			print("cart id Exists")
			if request.user.is_authenticated and cart_obj.user is None:
				cart_obj.user =request.user
				cart_obj.save()

		else:
			cart_obj = Cart.objects.new(user=request.user)
			new_obj=True
			print("created new cart ")
			print(cart_id)
			request.session['cart_id']=cart_obj.id
		return cart_obj,new_obj

	def new(self,user=None):
		user_obj=None
		if user is not None:
			if user.is_authenticated:
				user_obj=user
		return self.model.objects.create(user=user_obj)
		

class Cart(models.Model):
	user	 =models.ForeignKey(User,null=True,blank=True,on_delete=models.CASCADE)
	products =models.ManyToManyField(Product,blank=True)
	subtotal =models.DecimalField(default=0.00,decimal_places=3,max_digits=15)
	total 	 =models.DecimalField(default=0.00,decimal_places=3,max_digits=15)
	updated	 =models.DateTimeField(auto_now=True)
	timestamp=models.DateTimeField(auto_now_add=True)

	objects=CartManager()

	def __str__(self):
		return str(self.id)



def m2m_changed_cart_receiver(sender,instance,action,*args,**kwargs):
	print(action)
	if action == "post_add" or action == "post_remove" or action == "post_clear":
		products = instance.products.all()
		total = 0
		for x in products:
			total+=x.price
		if instance.subtotal!=total:
			instance.subtotal=total
			instance.save()

m2m_changed.connect(m2m_changed_cart_receiver,sender=Cart.products.through)


def pre_save_cart_receiver(sender,instance,*args,**kwargs):
	if instance.subtotal>0:
		instance.total=float(instance.subtotal) + float(8.5)
	else:
		instance.total=0
pre_save.connect(pre_save_cart_receiver,sender=Cart)

Django_Project/Django/Dev/ecommercefirst/src/carts/views.py
from django.shortcuts import render,redirect

from accounts.forms import LoginForm,GuestForm

from addresses.forms import AddressForm
from addresses.models import Address

from accounts.models import GuestEmail

from orders.models import Order
from billing.models import BillingProfile

from products.models import Product
from .models import Cart
# Create your views here.

def cart_home(request):
	cart_obj,new_obj = Cart.objects.new_or_get(request)

	return render(request,'carts/home.html',{"cart":cart_obj})

def cart_update(request):
	print(request.POST)
	# product_id = 4
	product_id = request.POST.get("product_id")
	if product_id is not None:
		try:
			product_obj = Product.objects.get(id=product_id)
		except Product.DoesNotExist:
			print("Show message to user , Product is gone")
			return redirect("cart:home")

		cart_obj,new_obj=Cart.objects.new_or_get(request)
		if product_obj in cart_obj.products.all():
			cart_obj.products.remove(product_obj)
		else:
			cart_obj.products.add(product_obj)
		request.session['cart_items']=cart_obj.products.count()
	return redirect("cart:home")


def checkout_home(request):
	cart_obj, cart_created = Cart.objects.new_or_get(request)
	order_obj = None
	if cart_created or cart_obj.products.count()==0:
		return redirect("cart:home")

	login_form = LoginForm()
	guest_form = GuestForm()
	address_form=AddressForm()
	print(request.session.items())
	shipping_address_id=request.session.get("shipping_address_id",None)
	billing_address_id=request.session.get("billing_address_id",None)
	
	billing_profile,billing_profile_created = BillingProfile.objects.new_or_get(request)
	address_qs = None
	if billing_profile is not None:
		if request.user.is_authenticated:
			address_qs = Address.objects.filter(billing_profile=billing_profile)

		order_obj,order_obj_created =  Order.objects.new_or_get(billing_profile,cart_obj)
		if shipping_address_id:
			print("ship begin")
			order_obj.shipping_address=Address.objects.get(id=shipping_address_id)
			del request.session["shipping_address_id"]
			print("ship end")
		if billing_address_id:
			order_obj.billing_address=Address.objects.get(id=billing_address_id)
			del request.session["billing_address_id"]
		if billing_address_id or shipping_address_id:
			order_obj.save()

	if request.method =="POST":
		# "some check that order is done"
		is_done = order_obj.check_done()
		if is_done:
			order_obj.mark_paid()
			request.session['cart_items']=0
			del request.session['cart_id']
			return redirect("cart:success")


	context={
		"object":order_obj,
		"billing_profile":billing_profile,
		"login_form":login_form,
		"guest_form":guest_form,
		"address_form":address_form,
		"address_qs":address_qs,
	}
	return render(request,"carts/checkout.html",context)



def checkout_done_view(request):
	context={}
	return render(request,"carts/checkout-done.html",context)

Django_Project/Django/Dev/ecommercefirst/src/carts/templates/carts/checkout-done.html
{% extends 'base.html' %}

{% block content %}

<div class="col-6 mx-auto">
  
  <h5 style="margin-top:200px;font-size:50px">THANK YOU,<br/> FOR YOU  ORDER</h5>

</div>


{% endblock %}

Django_Project/Django/Dev/ecommercefirst/src/carts/templates/carts/checkout.html
{% extends 'base.html' %}

{% block content %}
<!-- {{ object.order_id }} -- {{ object.cart }} -->

{% if not billing_profile %}
	<div class="container-fluid login_guest">
  	   <div class="row">    
   		 <div class="col-xs-12 col-sm-12 col-md-6 col- min-vh-100 left">
                    <div class="text-center">Account Login</div>
                    {% include "accounts/snippets/form.html" with form=login_form next_url=request.build_absolute_uri %}
    		</div>
    		<div class="col-xs-12 col-sm-12 col-md-6 col- min-vh-100">
     		  		<div class="text-center">Guest Login</div>
     		  		{% url "guest_register" as guest_register_url %}

					{% include "accounts/snippets/form.html" with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}				
    		</div>
    
  	    </div>
	</div>
{% else %}
		<!-- {{ object.shipping_address }} -->
		{% if not object.shipping_address %}
		<div class="row">
				<div class="col-sm">
					<p class="address">Shipping Address</p><hr>
				</div>
		</div>

		<div class="row">
			<div class="col-sm-12 col-md-8 col-lg-8 col-">  
				{% url "checkout_address_create" as checkout_address_create %}
				
				{% include "addresses/form.html" with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type="shipping"  %}
	 		</div>
	 		<div class="col-sm-12 col-md-4 col-lg-4 col-"> 
				{% url "checkout_address_reuse" as checkout_address_reuse %}

	 			{% include "addresses/prev_addresses.html" with address_qs=address_qs  next_url=request.build_absolute_uri address_type="shipping" action_url=checkout_address_reuse %}
	 		</div>
	 	</div>
		{% elif not object.billing_address %}
		<!-- {{ object.billing_address }} -->

		<div class="row">
				<div class="col-sm">
					<p class="address">Billing Address</p><hr>
				</div>
		</div>

		<div class="row">
			<div class="col-sm-12 col-md-8 col-lg-8 col-">  
			{% url "checkout_address_create" as checkout_address_create %}
			{% include "addresses/form.html" with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type="billing" %}
		    </div>
		    <div class="col-sm-12 col-md-4 col-lg-4 col-"> 
			{% url "checkout_address_reuse" as checkout_address_reuse %}

			{% include "addresses/prev_addresses.html" with address_qs=address_qs  next_url=request.build_absolute_uri address_type="billing" action_url=checkout_address_reuse %}
			</div>
	 	</div>
		{% else %}

		<div class="row">
				<div class="col-sm">
					<p class="address">Finalize Checkout</p><hr>
				</div>
		</div>
		<div class="col-sm-12 col-md-12 col-lg-12 col- px-5" style="font-size: 1.2em"> 
			<p>Cart Items: {% for product in object.cart.products.all %}{{ product }}{% if not forloop.last %}, {% endif %}{% endfor%}</p>
			<p>Shipping Address: <br><span style="margin-left: 70px">{{object.shipping_address.get_address }}</span> </p>
			<p>Billing Address: <br><span style="margin-left: 70px">{{object.billing_address.get_address }} </span></p>
			<p>Cart Total: {{ object.cart.total }}</p>
			<p>Shipping Total: {{object.shipping_total }} </p>
			<p>Order Total: {{object.total }} </p>
			<form class="form" method="POST" action="">{% csrf_token %}
				<button class="btn btn-5 btn-5b icon-cart" style = "padding: 12px 0; position:relative; width:150px;" type="submit"><span>Checkout</span></button>
			</form>
		</div>
	{% endif %}
{% endif %}

{% endblock %}

Django_Project/Django/Dev/ecommercefirst/src/carts/templates/carts/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>Cart</h1>
{%  if cart.products.exists %}
<table class="table font-weight-bolder">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product</th>
      <th scope="col">Product Name</th>
      <th scope="col">Product Price</th>
    </tr>
  </thead>

  <tbody>
  	{% for product in cart.products.all %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td><img src="{{product.image.url }}" style="max-width:100px;max-height:100px"></td>
      <td>
      <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
        {% include 'products/snippets/update-cart.html' with product=product cart=cart in_cart=True %}
      </td>
      <td>{{ product.price }}</td>
    </tr>
    {% endfor %}
    <tr>
   	  <td colspan="3"><b>Subtotal</b></td>
      <td>{{ cart.subtotal }}</td>
     </tr>
    <tr>
      <td colspan="3"><b>Total</b></td>
      <td>{{ cart.total }}</td>
     </tr>
     <tr>
      <td colspan="3"><b></b></td>
      <td>
        <a href='{% url "cart:checkout" %}'><button class="btn btn-5 btn-5b icon-cart" style ="position:relative;"><span>CheckOut</span></button></a>
      </td>
     </tr>
      
  </tbody>
</table>
{%  else %}
      <img src="{% static 'img/cart.png' %}" class="mx-auto" style=" display: block;height: 300px;width: 300px;"/>
{% endif %}
{% endblock %}